pid {{ .DataDir }}/nginx.pid;
daemon off;
worker_processes auto;

error_log syslog:server=unix:/dev/log warn;

events {
    worker_connections 1024;
}

http {
    access_log syslog:server=unix:/dev/log;
    include {{ .AppDir }}/nginx/etc/nginx/mime.types;
    default_type application/octet-stream;

    types_hash_max_size 2048;
    server_names_hash_bucket_size 64;
    client_max_body_size 100m;
    sendfile on;
    keepalive_timeout 65;
    gzip off;

    proxy_cache_path /dev/shm/onlyoffice_cache levels=1:2 keys_zone=onlyoffice_cache:10m max_size=100m inactive=1m use_temp_path=off;
    client_body_temp_path {{ .DataDir }}/nginx/client_body_temp;
    proxy_temp_path {{ .DataDir }}/nginx/proxy_temp;
    fastcgi_temp_path {{ .DataDir }}/nginx/fastcgi_temp;
    uwsgi_temp_path {{ .DataDir }}/nginx/uwsgi_temp;
    scgi_temp_path {{ .DataDir }}/nginx/scgi_temp;

    map $http_x_forwarded_proto $the_scheme {
        default $http_x_forwarded_proto;
        ""      $scheme;
    }

    map $http_x_forwarded_host $the_host {
        default $http_x_forwarded_host;
        ""      $host;
    }

    map $http_upgrade $proxy_connection {
        default upgrade;
        ""      close;
    }

    upstream docservice {
        server unix:{{ .DataDir }}/run/docservice.sock;
    }

    upstream web {
        server unix:{{ .DataDir }}/run/web.sock;
    }

    server {
        listen unix:{{ .CommonDir }}/web.socket;
        server_name _;
        set_real_ip_from unix:;

        root {{ .AppDir }}/documentserver/var-www/onlyoffice/documentserver;

        add_header X-Content-Type-Options nosniff;

        rewrite ^/[0-9]+\.[0-9]+\.[0-9]+[.\-][^/]+/(.*)$ /$1 last;

        location ~* ^/(web-apps|sdkjs|sdkjs-plugins|fonts|document-templates|dictionaries)(/.*)?$ {
            try_files $uri =404;
            expires 365d;
        }

        location /healthcheck {
            proxy_pass http://docservice/healthcheck;
            proxy_set_header Host $host;
        }

        location ~* ^/(coauthoring|info|doc|cache|ConvertService.ashx|GetFile|UploadService.ashx|webproxy)(/.*)?$ {
            proxy_pass http://docservice;
            proxy_http_version 1.1;
            proxy_set_header Host $the_host;
            proxy_set_header X-Forwarded-Host $the_host;
            proxy_set_header X-Forwarded-Proto $the_scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $proxy_connection;
        }

        location ~* ^/api/(file|callback)/ {
            include {{ .DataDir }}/config/proxy.conf;
            proxy_pass http://web;
        }

        location / {
            include {{ .DataDir }}/config/proxy.conf;
            proxy_pass http://web;
        }
    }
}
